### ISSUE TITLE
[NFR] Ability to position panel using absolute coordinates

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#10]
Hello,

First of all, huge thanks for jsPanel3 - what an amazing implementation!

I was trying to position my jsPanel at X & Y coordinates:

``` javascript
$.jsPanel({
    position: {
        left: '15px',
        top: '22px'
    }
});
```

Old [API doc](http://jspanel.de/v2.6.2/documentation/positioning.html) mentions such options - "Example 6", but that does not seem to work in v3.

Unrelated: there does not seem to be a place to ask questions - it would be nice if you could create a StackOverflow tag to talk about jsPanel3! :+1:

**Comment by Flyer53** [comment]
Hey there ... and thanks a lot :)

Version 3 has a completely new positioning engine. So left and top values for option.position don't work anymore. You have 2 options for you example:

``` javascript
$.jsPanel({
  position: {
    my: 'left-top',
    at: 'left-top',
    offsetX: 15,
    offsetY: 22
  }
});
```

or the same using a shorthand string:

``` javascript
$.jsPanel({
  position: 'left-top 15 22'
});
```

Check out http://jspanel.de/api/#option/position
If the docs are missing something... just tell me

**Comment by temuri416** [comment]
Thanks! That worked, should've figured it out myself :-)

I would only suggest that you update the documentation stating that absolute positioning does not work anymore and adding this example.
