### ISSUE TITLE
[NFR] Ability to "update" panel contents

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#11]
Hello,

This one needs a bit of explanation and it seems there are multiple problems :-)

The use case:
- User has an input interface that posts data via AJAX
- Server returns response that I would like to open in THE SAME instance of jsPanel (i.e. only one jsPanel is allowed)
- jsPanel instance **can be moved** around the screen AND **has close button**
- if panel is re-positioned and closed, I would like to open a new instance at exactly the same coordinates where it was closed (i.e. remember old panel's position)
- each time user re-submits data via AJAX and jsPanel is on the screen (i.e. not closed by the user) - I would like to update its content by the newly received data

My code so far:

``` javascript
var panelContents = 'String that arrived via AJAX Call';
var Panel = $.jsPanel({
    id: 'awesomeJsPanel',
    headerTitle: 'My Header',
    contentSize: 'auto auto',
    content: function(a, b) {
        // Some post-processing here...       
        return panelContents;
    }
});
```
### Step 1 - Initial page load

The first time user submits AJAX call everything is simple - at that point no jsPanel is shown and I display it for the first time.
### Step 2 - User did not close jsPanel, but moved it before submitting form again.

This time my goal is to find an existing instance of jsPanel (since it was moved I cannot just close it) and stick a new content into it. **How can I do this?** Theoretically, I could access DOM element, but I would like to reuse jsPanel's API to auto-reside panel, as the new content could be wider or taller.
### Step 3 - User moved jsPanel and then closed it before submitting form again.

Now I would like to reopen jsPanel exactly where it was closed before form was resubmitted. I still have the reference to it in `var Panel` (meaning I retained its position), but how do I open a new panel at exactly X & Y coordinates (@see #10) ?

Thanks a lot!

**Comment by Flyer53** [comment]
Hey there again ...
Let's talk about the positioning first. My approach to this issue would be as follows assuming you have only one panel which is appended to the body (you don't use option.container) and positioned left-top with some offsets:
- define a variable that holds the default position for this panel
- define a function that returns the current position of the panel in a format usable with option.position
- assign the function to option.onbeforeclose so that the value of the variable holding the position is updated when the panel is closed

Example code:

``` javascript
// variable holding the position is initialized with default position
var storedPosition = "left-top 100 60";

// function to update storedPosition
function getPosition(panel) {
    var panelOffset = panel.offset();
    var panelLeft = Math.floor(panelOffset.left - $(window).scrollLeft());
    var panelTop = Math.floor(panelOffset.top - $(window).scrollTop());
    return "left-top " + panelLeft + " " + panelTop;
}

// create panel
var test = $.jsPanel({
    position: storedPosition,
    onbeforeclose: function(panel) {
        storedPosition = getPosition(panel);
    }
});

// now move and close the panel. When you recreate the panel (with option.position set to
// stroredPosition) it's positioned where it was closed before.
```

**Another idea:** If you allow only one panel which might be recreated again and again, would it be an option to NOT let the user close the panel at all? The user could get the panel out of the way by minimizing it. And when normalizing the panel again it will be at the position the user moved it to before. So you don't need to worry about positioning issues. And you would have access to the panel content all the time.

**Comment by temuri416** [comment]
Hello again,

First of all - the code you suggested works perfectly. It covers the case when user is allowed to close the panel and I can reopen it at the last position.

Now, you've suggested removing "close" button and that ties into the (in)ability to update existing contents of jsPanel while doing auto-resizing. Calling jsPanel with an ID that already exists does nothing at all. How can I access "update" API method, if there is such?

Thank you!

**Comment by Flyer53** [comment]
Did you take a look at http://jspanel.de/api/#property/content ?
There are some examples of how to access the content of an existing panel and how to work with the content.
Basically it goes like this:
Create your panel and assign it to a variable

``` javascript
var myPanel = $.jsPanel();
```

Then access the content section with:

``` javascript
myPanel.content
```

The <code>content</code> property of the panel is the jquerified div element holding all the content. So if you for example would like to replace the first paragraph in the content section with another paragraph you could do this with:

``` javascript
$( 'p:eq(0)', myPanel.content ).replaceWith( '<p>Property content provides access to ...</p>' );
```

And after updating content autoresize content and panel if you like

``` javascript
myPanel.content.css({"width": "auto", "height": "auto"});
myPanel.resize("auto", "auto").reposition();
```

**Comment by temuri416** [comment]
Thanks for pointing to that page - I've missed that. Probably because you have two "property" links in the dropdown - http://jspanel.de/api/#option/content and http://jspanel.de/api/#property/content :)

Problem solved.

Much appreciated!
