### ISSUE TITLE
Footer content should be inside div not out of it

### ISSUE THREAD

**Issue by majksner** [Flyer53/jsPanel3#19]
![screen shot 2016-10-05 at 14 59 11](https://cloud.githubusercontent.com/assets/512355/19114009/67a584ee-8b0c-11e6-89ca-032ef558f87d.png)

**Comment by Flyer53** [comment]
You're right ... will be fixed with the next release.
Until then just set the overflow property of <code>.jsPanel-ftr</code> to "hidden".
Thanks for the report

**Comment by Flyer53** [comment]
In case you're interested take a look at the 3.4.0-alpha http://alpha.jspanel.de/

**Comment by Flyer53** [comment]
This issue is fixed with the release of version 3.4.0
