### ISSUE TITLE
Few improvements

### ISSUE THREAD

**Issue by majksner** [Flyer53/jsPanel3#2]
Hi,

First of all thanks for the hard work on jsPanel. I'm trying to implement jsPanel3 but I'm missing option to set z-index for the panel, I need to use higher z-index because of my layout. Also it would be great if possible to pass array of jsPanel instances to exportPanels method.

**Comment by Flyer53** [comment]
Hi there,
Thanks for the praise :)

#### z-index

This won't be a problem but you have to download an update first I just uploaded to the jsPanel homepage (not on GitHub yet): http://jspanel.de/downloads/jsPanel-3.0.0-RC1.zip
**Now you can set a "base" z-index for all your jsPanels as follows**
After loading the jsPanel script add the following 2 lines to your application js before you create the first panel:

``` javascript
jsPanel.ziBase = 500; // this is the lowest z-index a jsPanel will have
jsPanel.zi = 500; // has initially to be the same as ziBase
```

This example will result in jsPanels that have a z-index of at least 500. Use whatever value you need.

#### exportPanels()

That's something I have to evaluate first ...

**Comment by Flyer53** [comment]
### exportPanels()

I'm testing a small modification that would work as follows:

**add a custom css class to the panels you want to export like:**

``` javascript
$.jsPanel().addClass("jspanel-export");
```

**call .exportPanels() with the classname selector expression as argument like:**

``` javascript
jsPanel.exportPanels( ".jspanel-export" );
```

This should work quite well and needs only a minimal code modification.

**Comment by majksner** [comment]
Hi,

Thanks for the quick update. Another possible issue, I'm using latest RC release from bower.io, but It seems when event is triggered it's triggered 3 times if I have 3 instances of jsPanel. Is this a bug or it's normal behaviour. I believe only one event should be triggered for the instance I'm currently interacting with.

**Comment by Flyer53** [comment]
Well, I'm currently working on the event handling and there will be an
update tomorrow I guess.

But basically it's a matter of how you use the events. For example lets
look at _maximize_. There you have two ways to react to events:
**option.onmaximized** (http://jspanel.de/api/#option/onmaximized) and
the event **jspanelmaximized** (http://jspanel.de/api/#events)

Please take a close look at the api docs and check for an update tomorrow
afternoon I think.

2016-05-25 15:53 GMT+02:00 Nikola Majksner notifications@github.com:

> Hi,
> 
> Thanks for the quick update. Another possible issue, I'm using latest RC
> release from bower.io, but It seems when event is triggered it's
> triggered 3 times if I have 3 instances of jsPanel. Is this a bug or it's
> normal behaviour. I believe only one event should be triggered for the
> instance I'm currently interacting with.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Flyer53/jsPanel3/issues/2#issuecomment-221582995

## 

Stefan Sträßer
flych53g@gmail.com
http://stefanstraesser.eu/
http://jspanel.de/ http://stefanstraesser.com/
