### ISSUE TITLE
Any way to bottom align font Awsome icons in header?

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel3#20]
I have to use font awesome icons in my app (the glyph icons just wont show after i build my app - ive tried everything :)) but i find the way the icons are centered looks weird since the icons arent all the same height. Is there a way to bottom or top align the icons in the toolbar?

I tried building my own toolbar at the top but when i set the main toolbar to hidden then try and provide my own, my own toolbar is also hidden.. 

Thanks

**EDIT** i was just looking at it and i think the fact that the close icon is half the size of the full screen icon makes it look weird - maybe if it was the same size as the max button then it wouldnt stick out as much.. I use font awesome icons throughout my project and the icons are all the same size

**Comment by Flyer53** [comment]
Do you mean the jsglyph icons don't show? Make sure you have the **fonts** folder from the jsPanel download in the same folder where the jspanel css file is.

However, I tried one way that at least makes the font-awesome close icon the same size as the maximize icon. But line thickness increases as well ...

``` javascript
$.jsPanel({
  headerControls: {
    iconfont: 'font-awesome'
  },
  callback: function () {
    $('.jsPanel-btn-close span', this.header.controls).addClass('fa-lg').parent().css('margin-top', '-1px');
  }
});
```

The image below - hope it shows up - is what the result looks like

![alt text](http://res.cloudinary.com/stefanstraesser-eu/image/upload/v1475777861/modified-fa-close_l8bv5c.jpg)

I'll try a few other things as well ...

**Comment by whittssg** [comment]
Did you try fa-fw to fix the icons so they are all the same size? Thats what i use throughout my app to make things consistent:

http://fontawesome.io/examples/  

Look for "Fixed Width Icons" example

Thanks

**Comment by Flyer53** [comment]
As the example says, fa-fw only takes care of width of the span or i element. But it doesn't change the actual size of the icon itself.
You know, ther're zillions of nice icon sets out there. But I couldn't find a single one having good icons for the controls like I need for jsPanel. That's why I made my own little set.

Btw:
Code below shows how to have a header toolbar without the headerbar (title & controls)

``` javascript
$.jsPanel({
  headerToolbar: "One Two Three Four",
  callback: function(){
    $('.jsPanel-headerbar', this.header).css('display', 'none');
    $('.jsPanel-hdr-toolbar', this.header).css('cursor', 'move');
  },
  draggable: {
    handle: ".jsPanel-hdr-toolbar"
  }
});
```

**Comment by whittssg** [comment]
Yeh, your icons do look much better than the others.. I thought i had linked all of your fonts jsglyph  fonts correctly (they work great in dev mode) its soon as i compile and everything gets shoved into on JS file. Il have a mess around with the code you provided and will see if i can make something pretty from it. Thanks

**Comment by whittssg** [comment]
Tried to style them the way the rest of my app is done and that X still looks strange (il keep digging) - wish font awesome would make a new one for close.. Thanks for your help even though it wasnt really your libraries issue :)

![jspanel-fonta](https://cloud.githubusercontent.com/assets/6453857/19167910/b6cd1fbc-8bdb-11e6-845d-a1cd1301f5e3.png)

**Comment by Flyer53** [comment]
Always happy to help ... if I can ;)
Not absolutely perfect your solution, but not that bad either.
**Btw:** I found a small error in the css for <code>.jsPanel-controlbar</code> and in the function hiding/showing controls. No big thing and doesn't have anything to do with your issue. So I'll probably fix it with the 3.4.0 release I'm working on.

**Comment by whittssg** [comment]
Yeh i know.. i quickly shoved it together to see if the round uniformed icon backgrounds would pull away from the strange size differences with font awesome.. Il get someone looking good in the end im sure.. I checked font awesome github and there is still an issue open for a decent close icon from 2013 :(.. guess its not one of their priorities. On a plus side your code showed me away to get angular material components into the control bar ( i guess if had ever used jquery before i would have known that) - ive always tried to avoid it (but since i am including it now to use your amazing jspanel i might as well use it :) )

Wish i had found these icons before choosing font awesome:

https://design.google.com/icons/

My app is completely Angular Material and i think the icons look much better (and would fit my app more)

**Comment by Flyer53** [comment]
Found and commented also on the font-awesome issue requesting a close icon. Maybe it just needs a "magic" number of comments ....

And thanks for the hint on the Material Icons. Looks promising and I'll take a closer look :)

**Comment by Flyer53** [comment]
**Just included Material icons support in jsPanel 3.4.0-alpha1.**
Also not perfect but for the controls better than font-awesome I think.
Look yourself: http://alpha.jspanel.de/api/#option/headerControls Example 1a
I'm open to ideas on which icons to use ...
**Download 3.4.0-alpha1** from http://jspanel.de/downloads/jsPanel-3.4.0-alpha1.zip
Footer overflow and controls css is fixed in this version as well as far as I tested so far.

**Comment by whittssg** [comment]
They look much better than the font awesome ones.. Do you consider the alpha stable enough to use in prod? Thanks

**Comment by Flyer53** [comment]
I think yes! Just don't use the new option.delayClose yet. Not sure whether I leave it the way it is in the alpha.

**Comment by whittssg** [comment]
Seems to be working really well and i like the material icons. Thanks for all your hard work :)
![jspanelnewicons](https://cloud.githubusercontent.com/assets/6453857/19215749/79d0b7a0-8d74-11e6-9105-94df5c85b84c.jpg)

**Comment by Flyer53** [comment]
My pleasure .... looks really good 👍 
Any more ideas ... don't hesitate to tell me.
