### ISSUE TITLE
Minimize issue on new alpha version

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel3#22]
Hello,
The panel disappears when minimizing (to the bottom) in IE11.
http://alpha.jspanel.de/api/#option/headerControls
Try out the samples in the above link and then minimize them to the bottom. They will disappear. If you open enough panels and minimize them all so that they make 2 rows then they will reappear again.

Thanks

**Comment by Flyer53** [comment]
Hi again,
it's just a small error in the css. Will be fixed with the next update.
Have to admit that I'm a bit sloppy testing IE.
Thanks for reporting :)

**Comment by whittssg** [comment]
Thanks.. Can you post the CSS for the time being so i can override it?

**Comment by Flyer53** [comment]
http://beta.jspanel.de/downloads/jspanel-3.4.0-beta1-cssupdate.zip

**Comment by whittssg** [comment]
Awesome. Thanks so much :)

**Comment by Flyer53** [comment]
You're welcome ... but test it first ;)

**Comment by whittssg** [comment]
I tested - seems to work fine. Thanks

**Comment by Flyer53** [comment]
This issue is fixed in the latest beta
