### ISSUE TITLE
Minimize doesnt appear to be working on the RC1

### ISSUE THREAD

**Issue by huntmur** [Flyer53/jsPanel3#3]
Hi Stefan,

Just playing around with the new RC1 and the minimize button doesn't seem to be working.

Not sure if Im doing something wrong -- loaded the same test against 2.6.2 and that one is working fine.

Hope all is well.  :)

**Comment by huntmur** [comment]
found the solution for you :)

when you create the container:
$(document.body).append('<div id="jsPanel-replacement-container">');

it needs to be wrapped up with:
$(function() { 
      $(document.body).append('<div id="jsPanel-replacement-container">');
});

Then it seems to work perfect!! :)  not sure if this is the correct way you are doing it but it fixes the problem.

**Comment by huntmur** [comment]
I think I found the solution....

YOU HAVE:
$(document.body).append('< div id="jsPanel-replacement-container">');

SHOULD BE:
$(function() { 
$(document.body).append('< div id="jsPanel-replacement-container">');
});

(note: I add a space between < and div above so it would display here)

Anyway, seems to work perfect now but not sure if its the best fix, I will leave it to you :)

**Comment by huntmur** [comment]
What's interesting is that it seems to be working on your main site without any issues.  When I just included the basics Jquery & ui stuff and jspanel -- i get this issue.  If i switch back to 2.6.2 no issues. So this might be a context issue overall... anyway, my solution above might not be the answer because when I do only the basics it doesnt seem to be working for me in IE.  It does in chrome and firefox.  Again, 2.6.2 had no issues when I swapped them in instead.   Anyway, enough for today -- not sure ive really helped at all but I tried - Ill check back tomorrow.

**Comment by Flyer53** [comment]
Hi there again,
This seems all very strange to me. Never ever had any problems that a single control doesn't work, nor did I have another report like this.
<code>$(document.body)</code> in itself is already a function. Why wrap it in another function .... ?
Did you try simply <code>$("body")</code>? Works just as well.

Did you have any kind of error msg? And remember ... IE10 is not supported anymore. Version 3 needs at least IE11. You did not say which one you used.

At the moment I really don't know what to do about this. Could you email me a complete file that produces this error? Maybe I could reproduce this error then.

Take care, Stefan

**Comment by huntmur** [comment]
Hi Stefan,

Just emailed you the scripts. :) 

They are very small and running only the code.  I am guessing my issue is probably more related to context because I am wrapping up in $(function() { $.jsPanel(); });   to begin with. Anyway, thanks so much for all the help.  I really really like the new approach!  :)

Thanks, have a great day!
Jim

**Comment by Flyer53** [comment]
Ok Jim, I found the problem :)
Is it a bug? Yes and No. But most important: The solution is super easy and already included in the js file when you download the latest from the jsPanel homepage (not on GitHub yet). This time you need to exchange both the js and css files.
http://jspanel.de/downloads/jsPanel-3.0.0-RC1.zip

So what caused the problem!
You load your scripts in the HEAD element of the HTML. My script wants to add the replacement container to the body. But the body is not rendered yet when a script is loaded in the HEAD. Load the scripts at the end of the BODY element and everything is fine. As far as I read the js community that's the recommended way anyhow. However, I have to admit that I didn't see this potential problem and in the latest jsPanel js I moved the code adding the replacement container to a $(document).ready() block, so loading the script in the HEAD element works as well.

Take care, Stefan

**Comment by huntmur** [comment]
Ahh yes - of course.  That makes perfect sense.  It definitely wouldn't need to be in the head anyway for any practical purposes that I can think of. I can't believe I missed that. :)  I was just doing a quick test to check out the functionality and so I put that quick test together to check it out.

I will check it out -- thanks again Stefan - your the best!

-Jim
