### ISSUE TITLE
Problem with "Bootstrap Theme" in "Meteor JS"

### ISSUE THREAD

**Issue by thearabbit** [Flyer53/jsPanel3#30]
I have problem with `Bootstrap Them`, I base on `bootstrap@3.3.6` on `Meteor`.
```js
....
theme: "bootstrap-default"
```
don't work, please help me.

**Comment by Flyer53** [comment]
Do the other bootstrap themes work?
Can you show the complete code you use to generate the panel?
Does your bootstrap css include a bootstrap theme?

**Comment by thearabbit** [comment]
Yes bootstrap woke fine in my app.
`twbs:bootstrap` on `Meteor Package`.

**Comment by Flyer53** [comment]
If you want me to help you I need some more information and it would be nice if you answered all my questions. Just sying it doesn't work as expected is not enough to help you.
+ how about an error message?
+ what exactly does not work?
+ have you loaded a bootstrap theme?
+ do the panels work with another theme?
+ what does your code look like creating the panel?
+ can you post a screenshot of the panel?

**Comment by thearabbit** [comment]
Sorry for late to reply.
Please check your example [template/bootstrap3](https://github.com/Flyer53/jsPanel3/blob/master/template/bootstrap3.html).
It don't work for `theme: "bootstrap-success"`

**Comment by Flyer53** [comment]
Here is the live example of the mentioned file: http://jspanel.de/media/template/bootstrap3.html
Seems to work perfectly well as far as I see it.
So in case you still have a problem you need to provide some more detail.

**Comment by thearabbit** [comment]
Thanks I will try to create `example repo` for this, and sent you later.

**Comment by Flyer53** [comment]
@thearabbit 
Since you did not answer to this for more than 6 months now I consider this done
