### ISSUE TITLE
example in "../template/bootstrap3.html" don't work for "theme".

### ISSUE THREAD

**Issue by thearabbit** [Flyer53/jsPanel3#32]
example in "../template/bootstrap3.html" don't work for "Theme".

**Comment by Flyer53** [comment]
Here is the live example of the mentioned file: http://jspanel.de/media/template/bootstrap3.html
Seems to work perfectly well as far as I see it.
So in case you have a problem you need to provide some more detail.

**Comment by thearabbit** [comment]
It don't work on local (I download in my PC).

**Comment by Flyer53** [comment]
If you just open the html page from the local file system it doesn't work. But that's normal. You have to serve the page from a web server. Whether it's a local server on your PC (like XAMPP e.g.) or another one doesn't matter.

**Comment by thearabbit** [comment]
Thanks I will try to create `example repo` for this, and sent you later.

**Comment by Flyer53** [comment]
@thearabbit 
Since you did not answer to this for more than 6 months now I consider this done
