### ISSUE TITLE
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('btn btn-danger btn-sm') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by majksner** [Flyer53/jsPanel3#36]
It happens on my installation as well as on demo (Only on 3.6.0). Click on "Execute example 1" and you'll see error in browser console. http://jspanel.de/api/#option/footerToolbar

**Comment by Flyer53** [comment]
Hey there,
Bug is located, thanks for reporting. I think I'll have the fix online later today ...

Reason is in 3.6.0 I replaced some of the jQuery code with "native" javascript. In this particular case it's `Element.classList.add()` that can't handle a space seperated list of classnames to add.

**Comment by Flyer53** [comment]
Fixed and updated release 3.6.1 is online ...

**Comment by majksner** [comment]
Thanks.
