### ISSUE TITLE
access to toolbar buttons ?

### ISSUE THREAD

**Issue by xblox** [Flyer53/jsPanel3#37]
hi, 
how can we access the DOM nodes for the buttons ? I'd like to 'disable' some of them at some point. 

thanks a lot!

**Comment by Flyer53** [comment]
Hi there,
I assume you're talking about the standard controls like close, maximize and so on.
There is a built-in method to disable/enable those controls.
Take a look at http://jspanel.de/api/#method/headerControl

And with option.headerControls you can create the panel with already disabled or removed controls.
Take a look at http://jspanel.de/api/#option/headerControls example 3

Hope that helps ...

**Comment by xblox** [comment]
hi, thanks  a lot but no, its about the footer: 
options:{
 footerToolbar:[button defs]
}

i knew about the headerControl but it doesn't seem to exists for footer items (ok, cancel) which i need to add/remove a custom cssClass

thanks again :)

**Comment by Flyer53** [comment]
Ok, so if you create a footer toolbar as described in example 1 of the [option.footerToolbar api page](http://jspanel.de/api/#option/footerToolbar) you could do it as in the following example. For the demo it adds only one button.
```javascript
var arr = [
    {
        item:     "<button type='button'></button>",
        event:    "click",
        btnclass: "btn btn-danger btn-sm",
        btntext:  "Close",
        callback: function( event ){ event.data.close() }
    }
];

var panel = $.jsPanel({
    footerToolbar: arr,
});

// Disable close button in footer
$('.btn-danger', panel.footer).css({pointerEvents: 'none', opacity: 0.5, cursor: 'none'});

// Enable the button again
$('.btn-danger', panel.footer).css({pointerEvents: 'inherit', opacity: 1, cursor: 'pointer'});
```
In general it's up to you how to access the toolbar elements since you can put whatever content you want in the toolbar.

**Comment by xblox** [comment]
oki, sold! 
thanks a million, 
g
