### ISSUE TITLE
missing  jsPanel-3.7.0.zip  in jspanel.de 

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel3#39]
Hi stepan
I download the new version jsPanel3-3.7.0.zip from  GitHub
Be aware that in the site jspanel.de 
that  the zip file is Not Found

**Comment by Flyer53** [comment]
Ooops ... was just a typo in the zip filename

http://jspanel.de/downloads/jsPanel-3.7.0.zip

Thanks Avi :)
