### ISSUE TITLE
bootstrap button dropdown in jspanel

### ISSUE THREAD

**Issue by jyosh** [Flyer53/jsPanel3#4]
thanks for the wonderful library!!

currently I'm facing an issue with the bootstrap component - button dropdown, 
when using bootstrap button dropdown in jspanel the splitter button coming as smaller like in the attachment, even though required css & js files are included.

![jspanel issue](https://cloud.githubusercontent.com/assets/3429499/15672561/08f823be-274f-11e6-81c5-615b7536547a.png)

**Comment by Flyer53** [comment]
Hey there and thanks for the praise :)
Ok, as you can see below I don't face this issue. Checked with FF, Chrome, EDGE and IE11. I created the jsPanel with a bootstrap theme and added the split button dropdown sample from the bootstrap homepage (I assume bootstrap 3.x).
So it's difficult to say why you have this problem. Could there be any side effect with another library? Did you check which css overwrites the bootstrap css?
![bildschirmfoto am 2016-05-31 um 14 34 48](https://cloud.githubusercontent.com/assets/6769021/15674421/e31d67c4-273c-11e6-9e0c-e742ed2b6ad8.png)
I created the panel with the following code:

``` javascript
$.jsPanel({
  theme: "bootstrap-primary",
  border: "2px solid",
  content: `<div class="btn-group">
     <button type="button" class="btn btn-danger">Action</button>
     <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       <span class="caret"></span>
       <span class="sr-only">Toggle Dropdown</span>
     </button>
     <ul class="dropdown-menu">
       <li><a href="#">Action</a></li>
       <li><a href="#">Another action</a></li>
       <li><a href="#">Something else here</a></li>
       <li role="separator" class="divider"></li>
       <li><a href="#">Separated link</a></li>
     </ul>
     </div>`
});
```

**Comment by jyosh** [comment]
Thank you for the quick response.

Yeah, it was my mistake. I forgot <!DOCTYPE HTML> at the beginning of the page. It was working in an iframe that had the doctype so I suspected jspanel

**Comment by Flyer53** [comment]
You're welcome.
So I close this issue. Whenever you have any questions ... just go ahead and ask.
