### ISSUE TITLE
invisible dragged sub panel 

### ISSUE THREAD

**Issue by zotalegre** [Flyer53/jsPanel3#40]
try to drag a sub panel (inner panel) out of container panel, the sub panel is now invisible. release the mouse button - the sub panel is unreachable for ever. seems a bad idea to me...

**Comment by Flyer53** [comment]
To avoid your issue simply append the childpanel to the outer div of the parentpanel, not to the content section.
```javascript
var prt = $.jsPanel();

var chd = $.jsPanel({
  container: prt,
  contentSize: "200 80"
});
```
or, if you don't have issues with overflowing content, set the css overflow property of the parentpanel's content section to visible.

**Comment by zotalegre** [comment]
Thanks! (And, my bad, wasn't aware that you gave a fast answer, sorry)
BTW: being the solution pretty natural and obvious, problem is: Am I 97% dumb? or I am only 83% dumb and the documentation & examples are a bit faulty? :)
Thanks again for sharing great code,
Julio

**Comment by Flyer53** [comment]
Hi Julio,
no problem at all ... and my pleasure.
I don't think you're dumber than me or anyone else :smirk:
If the docs or examples are misleading/faulty please be so kind and point me to the place so I can correct it.
On the other hand, I personally don't see a reason why you would want to drag a panel outside of a parentpanel if you deliberately use it as "childpanel". In case you have some special usecase where this is useful I'd appreciate some explanation.

Have a nice one, Stefan
