### ISSUE TITLE
[BUG] jsPanel gets glued to mouse cursor and moves around with it

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#43]
Hi, 

I'm using jsPanel to display PDF files inline using Adobe Acrobat reader plugin.

While dragging the jsPanel instance with the PDF displayed inline, often mouse pointer would stutter for an instant and then jsPanel gets attached to it and follows pointer around even after I release mouse button.

Any idea what might be happening?

Thanks!

**Comment by Flyer53** [comment]
Hey there,
yes, I noticed this already. Also happens sometimes when the content is an iframe.
**What to do:** The easiest way to prevent this is to add some padding to the content section.
Funny: Just added an example displaying a PDF to the jsPanel version 4 preview docs yesterday (example 4, needs a moment to load the pdf)
http://alpha.jspanel.de/#options/option-content
I have yet to investigate the real reason behind this issue.

**Comment by Flyer53** [comment]
Ok, the solution above is not as good as I thought. It helps a bit with the resizeit interaction, but not really with dragit.
I already have a better solution I can incorporate in the script. Just need to make a few more tests and then I think I can release something in a few days.

**Comment by temuri416** [comment]
Fantastic, much appreciated!

**Comment by Flyer53** [comment]
Hi again,
I prepared a download package with a fix. Although it seems to work fine I'm not sure yet whether there isn't a better way to solve this. However, I would appreciate if you try it and give me some feedback.
http://jspanel.de/downloads/jspanel-3.9.1-alpha.zip
**Important:** This fix assumes you use the built-in interactions dragit and resizeit (not the jQuery UI interactions draggable and resizable)

**Comment by temuri416** [comment]
Thanks, I'll work on it later today! Will keep you posted.

**Comment by Flyer53** [comment]
Ok, I think I found a better fix. Please download the new archive and check whether it works in your scenario. http://jspanel.de/downloads/jspanel-3.9.1-alpha.zip
This new fix still assumes you use dragit/resizeit and not (jQuery UI draggable/resizable)

**Comment by temuri416** [comment]
Well... So far, so good. I can't break it here. Will try a different computer in a few hours.

**Comment by temuri416** [comment]
Nope... Can't break it!

**Comment by Flyer53** [comment]
Sounds good to me :)
I suggest you use it that way. The fix will be part of an official v3.9.1 release next week I guess.

**Comment by Flyer53** [comment]
Just **released v3.9.1** with the fix you already have.
I consider this issue as solved and close it. In case you still have problems just let me know.
Regards, Stefan

**Comment by temuri416** [comment]
thanks, most appreciated!

**Comment by temuri416** [comment]
BTW - where is your donation/support page?

**Comment by Flyer53** [comment]
Two options for a donation:
+ https://donorbox.org/jspanel
+ https://gratipay.com/jsPanel/

Would of course be very grateful for a small contribution :)

**Comment by temuri416** [comment]
There you go :-) Your efforts are appreciated.
