### ISSUE TITLE
[BUG] Panel resize gets glued to mouse cursor

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#44]
Hi,

1. Load http://jspanel.de/
2. This happens:

![zzz](https://user-images.githubusercontent.com/3987203/27517020-731f5f66-5992-11e7-9640-9bb81ad4c0b4.gif)

To repro (breaks 100% both in Chrome and Firefox):

1. Grab lower edge of a panel
2. Move cursor diagonally top & right
3. Make sure cursor is OUTSIDE of the panel
4. Release mouse button

That will make it stuck in panel vertical resize mode.

Thanks! :)

**Comment by Flyer53** [comment]
Ok, that's confirmed ...
but happens only when you move the mouse beyond a "reasonable" range. Should not be like that of course and I'll check what I can do. Thanks for the report :)

Btw: Also something that's not an issue with version 4 alpha.

**Comment by Flyer53** [comment]
Found something and prepared a download of another preliminary 3.9.2
[http://jspanel.de/downloads/jsPanel-3.9.2.zip](http://jspanel.de/downloads/jsPanel-3.9.2.zip)
Quick test on my machine works fine ...

**Comment by Flyer53** [comment]
**Released version 3.9.2**
I tested on FF, Chrome, Opera, Brave, Edge and IE11 and consider this isuue fixed.
