### ISSUE TITLE
Snapping.. Just a thought

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel3#46]
Hello, 
Anyway you could add a way to snap windows to the browser side.. So if i drag to the right it snaps to 50% of the screen etc.

Thanks

**Comment by Flyer53** [comment]
Hi there,
well, sure something I can think about.
I'll put it on the ToDo list. But I can't promise when, how or whether at all it will come. 

Anyhow, thanks for the idea 😄

**Comment by whittssg** [comment]
NP. I was looking at this codepen and just thought it would be cool if jspanel had something similar:
https://codepen.io/zz85/pen/gbOoVP

**Comment by Flyer53** [comment]
Nice pen, yep!
Starting tomorrow I'm away for about 2 weeks. When I'm back I'll look into this.

**Comment by Flyer53** [comment]
@whittssg 
Had some spare time. So I made a few experiments and ended with a test implementation of a snap feature within option.dragit for **version 4 alpha**. Maybe you want to take a look (example 4) and share your thoughts: http://alpha.jspanel.de/docs/#options/dragit

**Comment by whittssg** [comment]
Nice.. So i guess i would just manually resize the panel in the callback if i wanted it to sort of grow depending on where it get stuck to. Thanks for looking into it, its looking good.

**Comment by Flyer53** [comment]
That's the idea. Just uploaded a small **version 4 alpha** update to make it smooth when pulling away a snapped panel again. A minor drawback is that you have to release the mouse once if you want the panel to snap again. Here is an example code that resizes the panel upon snap and again when you pull it away again
```javascript
jsPanel.create({
    dragit: {       
        start: function(panel) {
            panel.resize('400 238');
        },
        snap: {
            type: 'all',
            sensitivity: 70,
            callback: function (panel, snappedTo) {
                $(this.content).empty().append('panel snapped to: ' + snappedTo);
                if (snappedTo === 'left-top') {
                    panel.resize({
                        width: window.innerWidth / 2,
                        height: window.innerHeight / 2
                    });
                } else if (snappedTo === 'right-top') {
                    panel.resize({
                        width: window.innerWidth / 2,
                        height: window.innerHeight / 2
                    }).reposition(snappedTo);
                }
            }
        }        
    }
});
```

**Comment by Flyer53** [comment]
@whittssg 
Just for info:
jsPanel version 4 will have a configurable **snap** parameter for **option.dragit** in order to have a panel snap to the corners or center positions of the sides. http://alpha.jspanel.de/docs/#options/dragit

**Comment by whittssg** [comment]
@Flyer53 Sounds good but i cant get the alpha demos to work. The panels wont drag and the buttons do not work (i tried latest firefox and latest chrome on win 7). Jspanel 3 works fine though. Thanks.

**Comment by Flyer53** [comment]
@whittssg 
Meanwhile I updated the v4 alpha several times. The latest update from yesterday includes a recoded snap feature within option.dragit http://alpha.jspanel.de/docs/#options/dragit (example 4)
Did you try it again? Still having problems getting v4 alpha to work? Any error messages? May be you can share some code and I might be able to help.

**Comment by whittssg** [comment]
@Flyer53 I guess it was just an issue in one of the earlier ones since it started working fine again the other week. Do you think this build is ok for prod use? Thanks

**Comment by Flyer53** [comment]
@whittssg 
I think so, yes! The code probably will change a little bit here and there ... but not the API.
Also the one or the other detail might be missing in the docs. Particularly I need to add some infos/examples to the docs of the global jsPanel props **pointerdown**, **pointermove** and **pointerup**. They might be useful when you have a footer toolbar with buttons e.g. that should work with touch AND mouse.
The latest from today is [v4.0..0-alpha.80](http://alpha.jspanel.de/downloads/jspanel-4-alpha.zip) with some more improvements of the snap feature.

**Comment by whittssg** [comment]
Looks good, two addition thoughts: 

- Any chance you can make it so you can drag back out without having to let go of the click and then drag again (i think it used to let you do this)

- Add another callback "entered snap zone" that fires before the panel is actually snapped (so mouse still down but panel in snap zone)

Thanks

**Comment by Flyer53** [comment]
@whittssg 
**no 1:**
It was that way once. But it had some nasty side effects I couldn't get rid of.
And you couldn't smoothly drag away a snapped panel. It sort of jumped back inside when the mouse cursor reached a position outside of the "snapsensitive " area. I didn't like that.
**no 2:**
Not exactly like you describe it because as soon as the panel is a single pixel below the threshold it will snap and there is nothing you can do about it. But something similar could be achieved I guess. I try to think of a usecase for this.... help me on that.

**Comment by whittssg** [comment]
@Flyer53 
Yeh sure..
For my use case it would work a little bit like how Windows 7 + handles dragging a window to the sides.. So if i dragged to the right it would animate out a  frame/border / outline showing where it was going to stick and expand to (so in jspanel, when the panel enters the snap zone i would get an event that would trigger my  animation to show where the panel was going to expand to (like windows does), if i move away then the frame / border / outline disappears and i can move to another snap zone (so it would need a snap zone entered / snap zone left event). If i chose to leave it in that dropzone (let go of the mouse click) then the snapped event would get fired (as it does now) and my panel would snap there and then in the callback id resize to the right hand side of the screen.

I thought about wanting to do it so that left and right take up half the screen, corners take up a 1/4 and top / bottom full screens it.

**Comment by whittssg** [comment]
even as it is now is i can still make it work without the outline (as you demoed in code earlier in this thread) but just thought it would be cool as an extra callback

**Comment by whittssg** [comment]
Ive been looking at a few other projects that implement the snapping feature and they seem to wait for the cursor to get into the snapzone before snapping (rather than the actual panel... windows does that as well) - would that help with issue number 1?

**Comment by Flyer53** [comment]
@whittssg 
Sounds pretty good ... absolutely worth to think about ... and I will think about it. 
Unfortunately I'm away for the next 8 days or so. I won't be able to any coding work on v4 alpha before I'm back ... be patient

**Comment by Flyer53** [comment]
@whittssg 
Found some extra time and just uploaded a v4 alpha 82 with with a complete recode of the snap feature that brings some changes:
+ panel will snap after mouseup (not immediately after entering snap zone)
+ "snapsensitive" area is shown with an outline when it becomes active
+ no need anymore to release the mouse to snap again at same position
+ each snap position can be turned off individually -> no type parameter anymore
+ custom callbacks for each snap position (see example 4)

http://alpha.jspanel.de/docs/#options/dragit
http://alpha.jspanel.de/downloads/jspanel-4-alpha.zip

I think this is a pretty good improvement of the snap feature and easily allows to mimic Windows behaviour. But I prefer to wait for the panel reference point to enter the snap zone, not the pointer.

... and the next v4 alpha update will have some fine tuning ...

**Comment by Flyer53** [comment]
Today I released jsPanel 4 beta 1 with a pretty good snap feature in its own GitHub repo.
So please open an issue in the new jsPanel v4 repo if needed.
