### ISSUE TITLE
Failed to restore header buttons

### ISSUE THREAD

**Issue by dikirill** [Flyer53/jsPanel3#47]
Hi,

Try to create panel with hidden header controls:

```javascript
var $jsPanel = $.jsPanel({
    headerControls: {minimize: 'remove', maximize: 'remove'}
});
```
Try now minimize (smallify) panel, and normalize it after by calling api:

```javascript
$jsPanel.normalize();
$jsPanel.front();
```

And you will get error in the console and all hidden buttons will reappear:

**Uncaught TypeError: Cannot read property 'style' of null**

Pointing to this function:
```javascript
        jsP.hideControls = function(sel) {
            Array.prototype.slice.call(jsP.header.controls[0].getElementsByClassName("jsPanel-btn")).forEach(function(item) {
                item.style.display = "block";
            });
            sel.forEach(function(item) {
---->          jsP.header.controls[0].querySelector(item).style.display = "none";
            });
        };
```

**Comment by Flyer53** [comment]
@dikirill 
Can you tell me a bit more about your setup please? I tried in FF, Chrome, EDGE, IE11 and could not reproduce the error you report.

**Comment by dikirill** [comment]
@Flyer53
You right, I was trying to rebuild this case in the isolated code, and couldn't repro.
I think I should close this issue.
