### ISSUE TITLE
JsPannel for Vue JS?

### ISSUE THREAD

**Issue by thearabbit** [Flyer53/jsPanel3#48]
JsPannel for Vue JS?

**Comment by Flyer53** [comment]
Short answer ... No
Long answer: jsPanel is a one man show. I'm not a professional programer and I do all this in my spare time. Furthermore there are quite a few javascript frameworks out there. Angular, React, Vue, Meteor ... just to name a few. Neither do I have the time nor the expertise to make a specific jsPanel version for those frameworks ... which I didn't use myself so far.
But anyone who has the knowledge and feels inclined to adapt jsPanel to a specific framework is welcome to do so.
**Btw:** The next major jsPanel version will be pure javascript without dependencies (not even jQuery). Therefore it should work with all of those frameworks.
Regards, Stefan

**Comment by thearabbit** [comment]
Very thanks, I will try

**Comment by RobertoMalatesta** [comment]
BTW: I did some loose tests integrating it with Angular 2/4/5 and OpenUI5 and it worked fine.

**Comment by Flyer53** [comment]
@RobertoMalatesta 
Very good to hear :smile:
Didn't hear of OpenUI5 so far ... will take a look.

**Comment by RobertoMalatesta** [comment]
@Flyer53 

> Didn't hear of OpenUI5 so far ... will take a look.

Honk me if you need some advice on it.
It's a valid alternative to Angular4 for enterprise apps (more stable, not so nicely documented).
I currently use both on different projects and I'm planning to create a series of examples on using UI5
programmatically with Typescript.
Here's an example I sketched up in Visual Studio Code to introduce it to Java developers (oxymoron).
[http://exedraos.com/esempio/progettoBaseUI5ConTypescript/](http://exedraos.com/esempio/progettoBaseUI5ConTypescript/)

It's relly minimal (sorry it had to be in Italian); click on demo.html to see the page running.

On my next private projects I'm currently inclined to avoid frameworks: today we have CSS FlexBox and Typescript, and once you have popup panels, a calendar and a few other components you can write a classical OO app in TS without the burden of a framework.

Ciao!,

-- R

**Comment by thearabbit** [comment]
I tried, but I don't understand how to pass `Vue Component` to `JsPanel Content`
[Example](https://jsfiddle.net/theara/wspx3spr/)
Please help me.

**Comment by Flyer53** [comment]
@thearabbit 
Within the code creating the jsPanel of the example you linked to above replace the line
```javascript
content: Child,
```
with
```javascript
content: Child.template,
```
and the content shows up.
But since I don't have any knowledge about Vue.js I don't know whether this is the proper fix for your problem.

**Comment by thearabbit** [comment]
after update [Example](https://jsfiddle.net/theara/wspx3spr/), it works fine.
But have a problem when the second click to show it doesn't have `JsPanel Content`?
1- First show
![image](https://user-images.githubusercontent.com/4495160/29237842-33578cd4-7f51-11e7-8da2-b0d9d5e299a2.png)
2- Second show
![image](https://user-images.githubusercontent.com/4495160/29237844-4108bdb2-7f51-11e7-97fa-3d3f4aded88d.png)

**Comment by Flyer53** [comment]
To me it seems like the same issue as before.
Replace
```javascript
content: $('.jspanel'),
```
with
```javascript
content: PanelCom.template,
```
and it works with every click.
But again, I'm not familiar with Vue.js. So it might be a good idea to get help from someone who is.

**Comment by thearabbit** [comment]
When I call `content: PanelCom.template` directly, I don't know how to pass `props data, emit event...` to this component?

**Comment by Flyer53** [comment]
Looks like you now need help from somebody having a good understanding of Vue.js. Sorry that I can't be of help here :(
