### ISSUE TITLE
jsPanel4.0 alpha jsPanel.extend() example panels don't minimize using the control

### ISSUE THREAD

**Issue by michaellions** [Flyer53/jsPanel3#49]
[http://alpha.jspanel.de/docs/#global/extend](url)
can't minimized?

**Comment by Flyer53** [comment]
Hey there, didn't notice this yet. Thanks for the report.
Strange though ... just the control doesn't work and I don't get any error messages.
Calling minimize() on the panel works.

**Comment by Flyer53** [comment]
@michaellions 
**Refers to jsPanel v4.0.0. alpha only !!**
Ok, this is fixed. But in order to fix it I needed to make a change to [jsPanel.getPanels()](http://alpha.jspanel.de/docs/#global/getPanels) making it a lot more flexible btw.

**Comment by michaellions** [comment]
well done!!
It works very well

**Comment by thearabbit** [comment]
How to install `version 4` via npm? (and how to import)

**Comment by thearabbit** [comment]
I tried to download file, but can't extract
![image](https://user-images.githubusercontent.com/4495160/29236670-f6cd6e46-7f37-11e7-939c-0bbdc7b9a618.png)

**Comment by Flyer53** [comment]
Version 4 is still in alpha stage and **NOT** available via npm or GitHub yet.
If you extract the latest alpha package the first level is a single folder with a name including the alpha build number. The second level has the folders you might know from previous downloads.
