### ISSUE TITLE
Why JsPanel don't have many "Github Star" and "NPM Install"?

### ISSUE THREAD

**Issue by thearabbit** [Flyer53/jsPanel3#50]
I used to use many `Modal package/plugin: BootBox, AlertifyJs, ...`, but not a full feature like `JsPanel`.
I think that `JsPanel` should have many `GitHub star` and `NPM Install`, Why???

**Comment by Flyer53** [comment]
Thanks for the praise 😃 
But that's a question I can't answer ... and, to be frank, didn't think about that much.

**Comment by thearabbit** [comment]
If you have some time, could you build it support `Vue, React or Meteor Package...`.
Bc all of this is the very popular framework.
