### ISSUE TITLE
[BUG] Dragging jsPanel outside top window margin causes JS error

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#51]
Hi,

1. Go to http://jspanel.de/
2. Grab "Hey there!" window and drag it slowly on top of the top window edge (over bookmarks, for example)
3. JS error is thrown:

![image](https://user-images.githubusercontent.com/3987203/30748943-e0e8f66e-9f7f-11e7-9687-5418dc01c4a0.png)

Browser: latest Chrome.

Thanks!

**Comment by Flyer53** [comment]
Hey Temuri,
Sorry for the late answer. Currently I'm moving and almost have no time to turn on the PC. Will stay like that for another week or so ...

So please be patient. The error msg is confirmed (did not show in Chrome 60) and I'll see what I can do.

Regards,
Stefan

**Comment by Flyer53** [comment]
@temuri416 
Just took a look at this issue. It happens only on the home page, not on the other pages. And it happens only with the first and last demo panels sliding in/out. So I think it's not an error in the jsPanel script but in my code to create/remove the demo panels. There also is no negative side effect as far as I can see.

**Comment by temuri416** [comment]
That's strange. I'm sure the same happens in my dev instance. I'll keep you posted.

**Comment by temuri416** [comment]
I've just confirmed it. It crashed exactly as I described above.

Version:
```
    version: '3.10.0',
    date: '2017-08-19 12:37',
```

**Comment by Flyer53** [comment]
Ok, I could reproduce the error on other pages/browsers as well now. Have to investigate ...
But what exactly do you mean with crash? I never had anything like a frozen or terminating browser. Functionality was always normal.

**Comment by Flyer53** [comment]
@temuri416 
I made a change to a preliminary v3.11.
So far I made only a few test on desktop but it seems to eliminate the error.
http://jspanel.de/downloads/jsPanel-3.11.0.zip
Maybe you can check in your env ...

**Comment by temuri416** [comment]
Works great, can't break it :)

Thanks!

**Comment by Flyer53** [comment]
Issue solved with v3.11.0 release
