### ISSUE TITLE
problem with contentAjax in asp.net

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel3#53]
Hello stefen
I need help from you

 I’m developing my projects with Microsoft Asp.net.

When I load a page using jspanel and   contentAjax, 
I am loading an entire .aspx page,
 Which includes events that destroy the events on the original page
The events operator is called __doPostBack
And is found on both pages on the main page, and on the page that I am loading.

I would like to make a call of jspanel and contentAjax
And to load only part of the page just a div from the target page 

Thanks
yours
avi hafner

**Comment by Flyer53** [comment]
Hi Avi,
Would it be possible for to use jQuery.load() instead of contentAjax in your case? jQuery.load() is able to load page fragments only.
Example:
```javascript
var p = $.jsPanel();
p.content.load('path/to/page/example.html #id_of_fragment');
```
See http://api.jquery.com/load/

Yours, Stefan

**Comment by AviHafner** [comment]
Hi Stefan
Great
All this week I am in meetings, and I am going to check yours advice  in the end of this week or next week

Yours
Avi Hafner

**Comment by AviHafner** [comment]
Hi Stefan
I am trying **without success** to remove JavaScript from the **_contentAjax_**

My code 
   contentAjax: {
                    type: "GET",
                    url: $(this).attr('href'),
                    done: function (data, textStatus, jqXHR, panel) {
                        $(this.content).find('*').each(function () {
                            if ($(this)[0].nodeName.toLowerCase() == 'script') {
                                console.log('this.nodeName=' + $(this)[0].nodeName.toLowerCase() + " id=" + $(this)[0].id)
                                console.log(' $(this)[0].innerHTML=' + $(this)[0].innerHTML)
                                $(this)[0].innerHTML = '';
                            }
                        });
                        $(panel.content).find("SCRIPT").empty();
                },
                    cache: false,
                    autoload: true,
                    always: function (data, textStatus, jqXHR, jsPanel) {
                        setTimeout(function () { Panel.resize('auto', 'auto'); }, 1000);
                    }
                },


Thanks
yours
avi hafner

**Comment by Flyer53** [comment]
Hi Avi,
If I understand you correctly you want to remove script tags from the loaded resource before the script tag content is executed:
The problem is you need to do that **before** the loaded data is appended to the panel content. To do this **jQuery.ajax()** has a setting called **[dataFilter](http://api.jquery.com/jQuery.ajax/)** you can use. **dataFilter** is a function that preprocesses the data returned from the XMLHttpRequest before it's passed on.

Please modify your contentAjax code as shown below:
```javascript
contentAjax: {
    url: $(this).attr('href'),
    dataFilter: function(data) { 
	// https://stackoverflow.com/questions/1441463/how-to-get-regex-to-match-multiple-script-tags
	var newData = data.replace(/<script\b[^>]*>([\s\S]*?)<\/script>/gmi, '');          
	return newData;
    },
    autoload: true,
    cache: false,
    always: function (data, textStatus, jqXHR, panel) {
        setTimeout(function () {
            panel.resize('auto', 'auto');
        }, 1000);
    }
}
```
Note:
+ added contentAjax parameter **dataFilter**
+ removed **done** callback
+ removed parameter **type** - defaults to "GET" anyhow

Please let me know whether this works for you.

Best regards,
Stefan

**Comment by AviHafner** [comment]
**amazing** thanks
you are **great**

Best regards,
Avi

**Comment by Flyer53** [comment]
Always a pleasure to help Avi

Take care,
Stefan
