### ISSUE TITLE
[Question]Is it possible to enable resize for panels under 'modal' style?

### ISSUE THREAD

**Issue by ZhaoC** [Flyer53/jsPanel3#54]
Hi Stefan,
I'm wondering is it possible to enable resize functionality when create a panel under ‘modal’ style. I notice that you explicitly exclude the ’jspanel-modal’ in method ‘resetZis()’ and other configurations for 'modal' style. Can I make the panel resizable without override your existing corresponding methods?
Thank you!

**Comment by Flyer53** [comment]
Yes you can:
```javascript
$.jsPanel({
    paneltype: 'modal',
    resizeit: true
});
```
will create a modal panel that is resizable (using the built-in **resizeit** option).
Or:
```javascript
$.jsPanel({
    paneltype: 'modal',
    resizeit: true,
    dragit: true
});
```
and it's also draggable via the built-in **dragit** option.

**Comment by ZhaoC** [comment]
got it, thanks a lot!
