### ISSUE TITLE
Modal minimize and normalize issues

### ISSUE THREAD

**Issue by genachka** [Flyer53/jsPanel3#55]
@Flyer53 loving what you've done with v3 and am anxious for v4 release that does away with jQuery dependency!

Using 3.10.0, I have a use case where I need to temporarily hide a modal dialog and then restore it. I thought I could leverage minimize and then normalize methods for this. But when I minimize I have two issues:
* It leaves the backdrop, I need it to disappear while it's minimized.
* Prior to minimize, I don't have any controls on the dialog (I close it on an event) so I don't want user to be able to close it. But when I minimize it, it now has a control to close it which I don't want.

Then when I call normalize, it errors out, looks like related to hiding controls:
```
Unhandled rejection TypeError: Cannot read property 'style' of null
    at eval (http://localhost/jspm_packages/npm/jspanel3@3.10.0/source/jquery.jspanel.js:3352:59)
    at Array.forEach (<anonymous>)
    at jQuery.fn.init.jsP.hideControls (http://localhost/jspm_packages/npm/jspanel3@3.10.0/source/jquery.jspanel.js:3351:17)
    at Object.normalize (http://localhost/jspm_packages/npm/jspanel3@3.10.0/source/jquery.jspanel.js:2233:15)
    at jQuery.fn.init.jsP.normalize (http://localhost/jspm_packages/npm/jspanel3@3.10.0/source/jquery.jspanel.js:3360:47)
```

**Comment by Flyer53** [comment]
@genachka Hey there and thanks a lot 😄 
Ok, your scenario is not a standard use case for a modal and I didn't consider that one so far.
But I think we can handle this ... just give me a bit time and I'll come back to you ...

**Comment by Flyer53** [comment]
@genachka 
If I get you right you don't need any controls. Not on the modal and not on the minimized replacement. All triggered by events? So I would suggest a solution that doesn't show the minimized replacement at all.

First download a preliminary v3.11 with a little bugfix in an internally used function to get rid of the error msg http://jspanel.de/downloads/jsPanel-3.11.0.zip

Then I have the following test code which seems to work:
```javascript
var m = $.jsPanel({
    paneltype: 'modal',
    headerControls: {
        controls: 'none'
    },
    minimizeTo: false, // prevents the minimized replacement
    callback: function (panel) {
        // show/hide modal backdrop depending on panel status
        $(document).on('jspanelstatuschange', function (event, id) {
            var status = panel.data('status');
            var modalId = '#jsPanel-modal-backdrop-' + id;
            if (status === 'minimized') {
                $(modalId).css('display', 'none');
            } else {
                $(modalId).css('display', 'block');
            }
        });
    }
});

window.setTimeout(function () {
    m.minimize();
}, 2000);

window.setTimeout(function () {
    m.normalize();
}, 4000);

window.setTimeout(function () {
    m.close();
}, 6000);
```

**Comment by Flyer53** [comment]
And this would be the modified code sample for v4.0.0 alpha without any jQuery
```javascript
var m = jsPanel.modal.create({
    headerControls: 'none',
    minimizeTo: false,
    onstatuschange: function () {
        var backdropId = '#jsPanel-modal-backdrop-' + this.id;
        if (this.status === 'minimized') {
            document.querySelector(backdropId).style.display = 'none';
        } else {
            document.querySelector(backdropId).style.display = 'block';
        }
    }
});

window.setTimeout(function () {
    m.minimize();
}, 2000);

window.setTimeout(function () {
    m.normalize();
}, 4000);

window.setTimeout(function () {
    m.close();
}, 6000);
```

**Comment by Flyer53** [comment]
@genachka 
I guess this issue is not of any relevance anymore and close it ...

**Comment by genachka** [comment]
@Flyer53 sorry I forgot all about this. :) but yes, no longer an issue thank you. Though I haven't tried it with 4.x yet (still on 3.x) but hopefully will be moving to your 4.x soon. Love what you've done with that!
