### ISSUE TITLE
Dragging a jsPanel containing an IFRAME problem.

### ISSUE THREAD

**Issue by RobertoMalatesta** [Flyer53/jsPanel3#60]
Hi @Flyer53 ,

I noticed that if start dragging a panel (*) containing an IFRAME and the mouse gets over the IFrame itself while dragging, the whole d'n'd mechanism goes beserk:
the cursor seems to be stuck inside the dragbar and no other action is possible but wandering around the screen with the panel glued to the cursor.

F5 is the only solution (similar to windows reboot)

Tell me if you need a working example of it.

-- Roberto

(*) very quickly, just trying to break things like always.

**Comment by Flyer53** [comment]
Hey Rob ...
did you switch to the latest 3.11 release already? It includes a fix of exactly this issue that should work fine.
http://jspanel.de/api/#option/contentIframe

And btw: I'm already working on a 3.12 which will improve usability on touch devices.

**Comment by RobertoMalatesta** [comment]
I will try it ASAP (baldmöglichst).

Besides, it's almost X-Mas and I told you I would have returned to JSPanel.

(After a long trip with OpenUI5, React, AngularJS -- don't ask me my opinion on these frameworks if you don't like hearing curses).

--R

**Comment by Flyer53** [comment]
@RobertoMalatesta  👍 
If I ever decide to dive into one of those frameworks I think my choice would be vue.js
But for now I simply don't see a reason for me to do so ...  and since I don't want you to develop a heart issue I won't ask 😏

**Comment by RobertoMalatesta** [comment]
nonononono.
frameworks are *evil*.
But... you'll have to learn it on your flesh, blood and bones.

**Comment by RobertoMalatesta** [comment]
>  I don't want you to develop a heart issue I won't ask

Every time I have to interact with some *SAP UI5 Specialist*,I then have to go to a full three hours of Wolfenstein as a therapy. :smile:

**Comment by Flyer53** [comment]
Wolfenstein ... a computer game, isn't it!?
My approach would be
![il_fullxfull 943192464_oi63](https://user-images.githubusercontent.com/6769021/32147175-520b87c8-bce3-11e7-92ac-cca1e5800a72.jpg)

**Comment by RobertoMalatesta** [comment]
I second that. :+1:

**Comment by RobertoMalatesta** [comment]
3.11 does not trap the mouse anymore, 
but I see some interference with IFRAME `overflow-y: scroll`.
Sometimes the middle scroll button just stops working.

It seems to happen in Chrome but not in FF:
After some dragging of a panel the scroll event is gone.

Tell me if you need an ad hoc example.

--R

**Comment by Flyer53** [comment]
Mmmmh ... I'm not sure whether I understand you. I see on Chrome and FF that scrolling the iFrame stops when the cursor moves too far away from the scroll handle while scrolling without releasing the mouse. But resumes scrolling when you move in again.

Is that what you mean?

**Comment by RobertoMalatesta** [comment]
My fault: I was not clear and the condition is difficult to describe by words only.
I will write down a small test case-

--R

**Comment by Flyer53** [comment]
@RobertoMalatesta 
I guess this issue is not of any relevance anymore and close it ...

**Comment by RobertoMalatesta** [comment]
Hi @Flyer53 
I suppose so.
Nobody else fond it relevant or hit at it.
Currently I'm not using JSPanel (too baaaad, I gotta have time to go back at it :smiley_cat:  ) 
Thanks for the support.
--Rob
