### ISSUE TITLE
[Feature Request] Tabbed panel

### ISSUE THREAD

**Issue by simon1tan** [Flyer53/jsPanel3#62]
Any plans on tabbed panels in the future?  This is where all panels open full size, and tabs at the top allow user to choose which panel is visible. 
For example, see https://golden-layout.com/examples/#21c1fbbbfaebca00a7183c9707bbef98.

**Comment by Flyer53** [comment]
@simon1tan 
Hey there ... and thanks for your input.
No, so far I did not think about such a feature.
Did you consider using e.g. Bootstrap tabs as panel content? There is a simple example in the docs for jsPanel v4 beta. Scroll down to example 4 http://jspanel.de/docs/#options/contentAjax

**Comment by Flyer53** [comment]
@simon1tan 
Since you didn't answer to this issue for months I consider it not relevant anymore and close the issue
