### ISSUE TITLE
JsPanel4 Support of Microsoft ie11

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel3#64]
Hi Stephen
At our university the administration people uses heavy in IE11.
At the address
[developer mozilla](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Example) see the **Example** paragraph, 
In this page you can find the few rows to add support to ie11 with missing **CustomEvent**

At this address
[Working jspanel4 Sample in ie11](http://www.admin.technion.ac.il/avi/jspanel-4-beta/)
You can find the latest working samples of jspanel4 with IE11.

Yours
Hafner Avi

**Comment by Flyer53** [comment]
Hi Avi,
thanks a lot for your input :)
But it's not that easy. IE11 already has a customEvent object, but you can't use the constructor method to add a new custom event. See https://caniuse.com/#feat=customevent for a quick description.

Officially jsPanel v4 will not support IE11. There are some more minor issues beside custom events that would require extra compatibility code only for IE. But if you want to switch to jsPanel v4 I could provide you a file including custom events for IE11. Just let me know ...

Best regards,
Stefan

**Comment by AviHafner** [comment]
Hi Stephen
I would be very happy to receive file that including custom events for IE11.
I think that such an addition should be part of jspael4 for every programmer with needs like mine.

Yours
Avi hafner

**Comment by Flyer53** [comment]
Hi Avi,
Ok ... I'll check how much extra code it needs to restore jsPanel v4 compatibility with IE11.
Meanwhile you can download and try the following package
http://jspanel.de/downloads/jspanel-4-beta.zip
It should basically work with IE11. But I'm sure there will be the one or the other minor issue (especially with the css I think). Just try it and let me know.

Best regards,
Stefan

PS: Please file issues related to **jsPanel v4** at https://github.com/Flyer53/jsPanel4

**Comment by ghost** [comment]
Hi Stephen,
Work like a charm on Chrome and FF.
I tried this version jspanel-4-beta.1.16 on IE 11.125.16299.0.
We have a error script445 on line 1905 (Events). The script stop on variable new CustomEvent.

Best regards.
Alex

**Comment by Flyer53** [comment]
Hi Alex,
please try http://jspanel.de/downloads/jspanel-4-beta.zip
and note that my IE11 that I test on has the version 11.786.15063.0
jspanel-4-beta.1.18 seems to work quite well without any errors concerning CustomEvents

But remember that I initially didn't want **jsPanel v4** to support IE11 at all. So there might still be some issues. If you find anything ... let me know.

Best Regards,
Stefan

**Comment by Flyer53** [comment]
Issue closed as it relates to jsPanel version 4.
If needed for jsPanel version 4 please open an issue at https://github.com/Flyer53/jsPanel4/issues

**Comment by ggcaponetto** [comment]
Hello, I faced the same issue (@AviHafner ) and the only error preventing me to use the **jsPanel v4** was the lack of Promise support in **IE11**. I solved importing a polifyll (version 7.1.2)(https://github.com/taylorhakes/promise-polyfill/releases). Hope it helped.
