### ISSUE TITLE
YouTube Playback support out of the box

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel3#67]
Hello,

Does jsPanel offer YouTube and Vimeo integration out of the box?

Thanks

Hugo

**Comment by Flyer53** [comment]
Hi Hugo,

YouTube and Vimeo offer embed code via the share button you can use with `option.content` like:
```javascript
$.jsPanel({
    content: '<iframe width="560" height="315" src="https://www.youtube.com/embed/tGdL-34L-GE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>',
    contentSize: {width: 'auto', height: 'auto'},
    headerTitle: "YouTube video",
    theme: "#F8D306"
});
```
But so far I did not implement anything specific concerning YouTube/Vimeo. What exactly is it you have in mind?
I'm always happy to get new ideas ...

Regards,
Stefan

**Comment by Flyer53** [comment]
@inglesuniversal 
You did not respond to this issue for more than 5 months. So I assume it's not relevant anymore...
