### ISSUE TITLE
Resizing Panel when 'rolled up' causes issues 

### ISSUE THREAD

**Issue by JeremyBYU** [Flyer53/jsPanel3#7]
Hi!
Great work on this project. However I am having a little issue.

Problem: 
Horizontally resizing the panel when it is 'rolled up' causes ui issues.  The color of the panel corrupt the content.
See the following picture.

![image](https://cloud.githubusercontent.com/assets/6628085/16204401/3addea04-36e4-11e6-9983-a69a62c7b3c0.png)

![image](https://cloud.githubusercontent.com/assets/6628085/16204431/5654ce92-36e4-11e6-9703-ef8273cdde3b.png)

Details:
OS: Windows 7 
Browser: Chrome 51.0.2704.84 m

**Comment by Flyer53** [comment]
Thank you very much :) 
And thanks for the report. Please give me a few days to take a look at this issue. I'm currently on vacation and the only Internet access I have is the mobile phone from time to time. 

Regards, Stefan

**Comment by JeremyBYU** [comment]
No problem! Enjoy your vacation!

**Comment by Flyer53** [comment]
Hi Jeremy,
this issue is confirmed and I know what happens. Seems to be something cuased by the jQuery UI resizable feature. Just have to figure out the best way to fix this ...

**Comment by Flyer53** [comment]
This issue is fixed, although I have to test the fix some more since I tested only on FF so far. If you want to test yourself you can download 3.0.1 beta
http://jspanel.de/downloads/jsPanel-3.0.1-beta.zip
This also includes a modified css file concerning the <code>@font-face</code> rule.

**Comment by JeremyBYU** [comment]
Tested the new beta and I am not having this issue anymore. Way to go!

Testing Environment:
OS: Windows 7
Browsers: IE11 and Chrome

However while testing IE11 I found separate bug I will report.
