### ISSUE TITLE
Bring to front auto

### ISSUE THREAD

**Issue by yarekc** [Flyer53/jsPanel3#73]
Hi,
I use v3.9
Is there a way of bring to front with front() function when I click on the JSPanel ?

I do not keep any variable reference to a created jsPanel, so I cannot just use

panel1.front();

Would be great to have a "autoBringFront" property : now when I click on a jsPanel that is behind, nothing happens

Regards

**Comment by yarekc** [comment]
Sorry for disturbing you.. just found it works fine !

**Comment by Flyer53** [comment]
Don't worry ... 😏 
and a Happy New Year
