### ISSUE TITLE
IE11 Minimize UI Issues

### ISSUE THREAD

**Issue by JeremyBYU** [Flyer53/jsPanel3#9]
Hey! While testing JSPanel I noticed another issue(I confirmed that the issue existed before 3.01 beta).

When a user minimizes JS Panel it collapses and goes to the bottom left section of the screen. However in IE11 the `title bar` is skewed from the icons. See the below image;

![image](https://cloud.githubusercontent.com/assets/6628085/16343752/906e24b2-39fe-11e6-8f8f-2ac000337a96.png)

Environment:
OS: Windows
Browser: IE11 (Chrome works fine)

Thanks

**Comment by Flyer53** [comment]
Confirmed, though this is somehow strange. It doesn't happen with all panels. Anyway, I fixed this issue and you can download a new 3.0.1 beta. It's only the css file you have to swap.
http://jspanel.de/downloads/jsPanel-3.0.1-beta.zip
